import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';

import '../../services/payslip_pdf_service.dart';

class PayslipsScreen extends StatefulWidget {
  const PayslipsScreen({super.key});

  @override
  State<PayslipsScreen> createState() =>
      _PayslipsScreenState();
}

class _PayslipsScreenState
    extends State<PayslipsScreen> {
  final TextEditingController _searchController =
      TextEditingController();

  String _searchText = '';
  String _statusFilter = 'all';
  String? _processingPayslipId;

  @override
  void dispose() {
    _searchController.dispose();
    super.dispose();
  }

  Future<Map<String, dynamic>>
      _loadCurrentUserSnapshot() async {
    final User? user =
        FirebaseAuth.instance.currentUser;

    if (user == null) {
      throw StateError(
        'Your login session has expired.',
      );
    }

    final DocumentSnapshot<Map<String, dynamic>>
        userDocument =
        await FirebaseFirestore.instance
            .collection('users')
            .doc(user.uid)
            .get();

    final Map<String, dynamic> userData =
        userDocument.data() ??
            <String, dynamic>{};

    return <String, dynamic>{
      'uid': user.uid,
      'fullName':
          userData['fullName']?.toString().trim().isNotEmpty ==
                  true
              ? userData['fullName'].toString().trim()
              : user.displayName ?? 'Authenticated User',
      'email':
          userData['email']?.toString().trim().isNotEmpty ==
                  true
              ? userData['email'].toString().trim()
              : user.email ?? '',
      'role':
          userData['userRole']?.toString().trim().isNotEmpty ==
                  true
              ? userData['userRole'].toString().trim()
              : userData['role']?.toString().trim().isNotEmpty ==
                      true
                  ? userData['role'].toString().trim()
                  : 'hr',
    };
  }

  DocumentReference<Map<String, dynamic>>?
      _payrollReference(dynamic value) {
    if (value is DocumentReference<
        Map<String, dynamic>>) {
      return value;
    }

    if (value is DocumentReference) {
      return FirebaseFirestore.instance.doc(
        value.path,
      );
    }

    if (value is String &&
        value.trim().isNotEmpty) {
      final String path = value.trim();

      if (path.contains('/')) {
        return FirebaseFirestore.instance.doc(path);
      }

      return FirebaseFirestore.instance
          .collection('payroll')
          .doc(path);
    }

    return null;
  }

  Future<void> _approvePayslip({
    required String payslipId,
    required DocumentReference<Map<String, dynamic>>
        payslipReference,
    required Map<String, dynamic> data,
  }) async {
    if (_processingPayslipId != null) {
      return;
    }

    final DocumentReference<Map<String, dynamic>>?
        payrollReference =
        _payrollReference(data['payrollId']);

    if (payrollReference == null) {
      _showMessage(
        'The associated payroll reference is missing.',
        error: true,
      );
      return;
    }

    try {
      final Map<String, dynamic> approver =
          await _loadCurrentUserSnapshot();

      if (!mounted) {
        return;
      }

      final TextEditingController remarksController =
          TextEditingController();

      final bool? confirmed =
          await showDialog<bool>(
        context: context,
        builder: (
          BuildContext dialogContext,
        ) {
          return AlertDialog(
            title: const Text(
              'Approve Payslip',
            ),
            content: SingleChildScrollView(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment:
                    CrossAxisAlignment.start,
                children: <Widget>[
                  _DialogInfoRow(
                    label: 'Employee',
                    value:
                        data['employeeName']?.toString() ??
                            'Employee',
                  ),
                  _DialogInfoRow(
                    label: 'Generated by',
                    value: _actorLabel(
                      data['generatedBy'] ??
                          data['preparedBy'],
                    ),
                  ),
                  _DialogInfoRow(
                    label: 'Approving as',
                    value: _actorLabel(approver),
                  ),
                  _DialogInfoRow(
                    label: 'Net pay',
                    value:
                        'PHP ${_readNumber(data['netPay']).toStringAsFixed(2)}',
                  ),
                  const SizedBox(height: 14),
                  TextField(
                    controller: remarksController,
                    minLines: 2,
                    maxLines: 4,
                    decoration:
                        const InputDecoration(
                      labelText:
                          'Approval remarks (optional)',
                      alignLabelWithHint: true,
                      border: OutlineInputBorder(),
                    ),
                  ),
                  const SizedBox(height: 10),
                  const Text(
                    'Approving updates both the payslip and its related payroll record.',
                    style: TextStyle(
                      color: Color(0xFF667085),
                      fontSize: 12,
                      height: 1.4,
                    ),
                  ),
                ],
              ),
            ),
            actions: <Widget>[
              TextButton(
                onPressed: () {
                  Navigator.of(dialogContext)
                      .pop(false);
                },
                child: const Text('Cancel'),
              ),
              FilledButton.icon(
                onPressed: () {
                  Navigator.of(dialogContext)
                      .pop(true);
                },
                style: FilledButton.styleFrom(
                  backgroundColor:
                      const Color(0xFF1F5CF5),
                  foregroundColor: Colors.white,
                ),
                icon: const Icon(
                  Icons.check_circle_outline,
                ),
                label: const Text('Approve'),
              ),
            ],
          );
        },
      );

      final String remarks =
          remarksController.text.trim();
      remarksController.dispose();

      if (confirmed != true) {
        return;
      }

      setState(() {
        _processingPayslipId = payslipId;
      });

      final Map<String, dynamic> update =
          <String, dynamic>{
        'status': 'approved',
        'approvedBy': approver,
        'approvedAt':
            FieldValue.serverTimestamp(),
        'approvalRemarks':
            remarks.isEmpty ? null : remarks,
        'returnedBy': FieldValue.delete(),
        'returnedAt': FieldValue.delete(),
        'returnReason': FieldValue.delete(),
        'updatedAt':
            FieldValue.serverTimestamp(),
      };

      final WriteBatch batch =
          FirebaseFirestore.instance.batch();

      batch.update(
        payslipReference,
        update,
      );

      batch.update(
        payrollReference,
        update,
      );

      await batch.commit();

      _showMessage(
        'Payslip approved successfully.',
        error: false,
      );
    } catch (error) {
      _showMessage(
        'Unable to approve payslip: $error',
        error: true,
      );
    } finally {
      if (mounted) {
        setState(() {
          _processingPayslipId = null;
        });
      }
    }
  }

  Future<void> _returnPayslip({
    required String payslipId,
    required DocumentReference<Map<String, dynamic>>
        payslipReference,
    required Map<String, dynamic> data,
  }) async {
    if (_processingPayslipId != null) {
      return;
    }

    final DocumentReference<Map<String, dynamic>>?
        payrollReference =
        _payrollReference(data['payrollId']);

    if (payrollReference == null) {
      _showMessage(
        'The associated payroll reference is missing.',
        error: true,
      );
      return;
    }

    try {
      final Map<String, dynamic> returner =
          await _loadCurrentUserSnapshot();

      if (!mounted) {
        return;
      }

      final TextEditingController reasonController =
          TextEditingController();

      final String? reason =
          await showDialog<String>(
        context: context,
        builder: (
          BuildContext dialogContext,
        ) {
          String? validationMessage;

          return StatefulBuilder(
            builder: (
              BuildContext context,
              void Function(
                void Function(),
              ) setDialogState,
            ) {
              return AlertDialog(
                title: const Text(
                  'Return Payslip',
                ),
                content: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: <Widget>[
                    const Text(
                      'Explain what must be corrected before this payroll can be approved.',
                      style: TextStyle(
                        color: Color(0xFF667085),
                        height: 1.4,
                      ),
                    ),
                    const SizedBox(height: 14),
                    TextField(
                      controller: reasonController,
                      minLines: 3,
                      maxLines: 5,
                      autofocus: true,
                      decoration: InputDecoration(
                        labelText:
                            'Reason for return',
                        alignLabelWithHint: true,
                        errorText:
                            validationMessage,
                        border:
                            const OutlineInputBorder(),
                      ),
                    ),
                  ],
                ),
                actions: <Widget>[
                  TextButton(
                    onPressed: () {
                      Navigator.of(dialogContext)
                          .pop();
                    },
                    child: const Text('Cancel'),
                  ),
                  FilledButton.icon(
                    onPressed: () {
                      final String value =
                          reasonController.text.trim();

                      if (value.isEmpty) {
                        setDialogState(() {
                          validationMessage =
                              'Please enter a reason.';
                        });
                        return;
                      }

                      Navigator.of(dialogContext)
                          .pop(value);
                    },
                    style: FilledButton.styleFrom(
                      backgroundColor:
                          const Color(0xFFD92D20),
                      foregroundColor:
                          Colors.white,
                    ),
                    icon: const Icon(
                      Icons.undo_rounded,
                    ),
                    label: const Text('Return'),
                  ),
                ],
              );
            },
          );
        },
      );

      reasonController.dispose();

      if (reason == null ||
          reason.trim().isEmpty) {
        return;
      }

      setState(() {
        _processingPayslipId = payslipId;
      });

      final Map<String, dynamic> update =
          <String, dynamic>{
        'status': 'returned',
        'returnedBy': returner,
        'returnedAt':
            FieldValue.serverTimestamp(),
        'returnReason': reason.trim(),
        'approvedBy': FieldValue.delete(),
        'approvedAt': FieldValue.delete(),
        'approvalRemarks': FieldValue.delete(),
        'updatedAt':
            FieldValue.serverTimestamp(),
      };

      final WriteBatch batch =
          FirebaseFirestore.instance.batch();

      batch.update(
        payslipReference,
        update,
      );

      batch.update(
        payrollReference,
        update,
      );

      await batch.commit();

      _showMessage(
        'Payslip returned for correction.',
        error: false,
      );
    } catch (error) {
      _showMessage(
        'Unable to return payslip: $error',
        error: true,
      );
    } finally {
      if (mounted) {
        setState(() {
          _processingPayslipId = null;
        });
      }
    }
  }

  Future<void> _releasePayslip({
    required String payslipId,
    required DocumentReference<Map<String, dynamic>>
        payslipReference,
    required Map<String, dynamic> data,
  }) async {
    if (_processingPayslipId != null) {
      return;
    }

    final DocumentReference<Map<String, dynamic>>?
        payrollReference =
        _payrollReference(data['payrollId']);

    if (payrollReference == null) {
      _showMessage(
        'The associated payroll reference is missing.',
        error: true,
      );
      return;
    }

    try {
      final Map<String, dynamic> releaser =
          await _loadCurrentUserSnapshot();

      if (!mounted) {
        return;
      }

      final bool? confirmed =
          await showDialog<bool>(
        context: context,
        builder: (
          BuildContext dialogContext,
        ) {
          return AlertDialog(
            title: const Text(
              'Release Payslip',
            ),
            content: Text(
              'Release the approved payslip for '
              '${data['employeeName']?.toString() ?? 'this employee'}? '
              'The employee will be able to view and download it.',
            ),
            actions: <Widget>[
              TextButton(
                onPressed: () {
                  Navigator.of(dialogContext)
                      .pop(false);
                },
                child: const Text('Cancel'),
              ),
              FilledButton.icon(
                onPressed: () {
                  Navigator.of(dialogContext)
                      .pop(true);
                },
                style: FilledButton.styleFrom(
                  backgroundColor:
                      const Color(0xFF039855),
                  foregroundColor: Colors.white,
                ),
                icon: const Icon(
                  Icons.send_outlined,
                ),
                label: const Text('Release'),
              ),
            ],
          );
        },
      );

      if (confirmed != true) {
        return;
      }

      setState(() {
        _processingPayslipId = payslipId;
      });

      final Map<String, dynamic> update =
          <String, dynamic>{
        'status': 'released',
        'releasedBy': releaser,
        'releasedAt':
            FieldValue.serverTimestamp(),
        'updatedAt':
            FieldValue.serverTimestamp(),
      };

      final WriteBatch batch =
          FirebaseFirestore.instance.batch();

      batch.update(
        payslipReference,
        update,
      );

      batch.update(
        payrollReference,
        update,
      );

      await batch.commit();

      _showMessage(
        'Payslip released successfully.',
        error: false,
      );
    } catch (error) {
      _showMessage(
        'Unable to release payslip: $error',
        error: true,
      );
    } finally {
      if (mounted) {
        setState(() {
          _processingPayslipId = null;
        });
      }
    }
  }

  Future<void> _downloadPayslip({
    required String payslipId,
    required Map<String, dynamic> data,
  }) async {
    try {
      await PayslipPdfService.sharePayslip(
        data: data,
        payslipId: payslipId,
      );
    } catch (error) {
      _showMessage(
        'Unable to generate payslip PDF: $error',
        error: true,
      );
    }
  }

  void _showMessage(
    String message, {
    required bool error,
  }) {
    if (!mounted) {
      return;
    }

    ScaffoldMessenger.of(context)
      ..hideCurrentSnackBar()
      ..showSnackBar(
        SnackBar(
          content: Text(message),
          behavior: SnackBarBehavior.floating,
          backgroundColor: error
              ? const Color(0xFFD92D20)
              : const Color(0xFF039855),
        ),
      );
  }

  bool _matches(
    QueryDocumentSnapshot<Map<String, dynamic>>
        document,
  ) {
    final Map<String, dynamic> data =
        document.data();

    final String status =
        _normalizeStatus(data['status']);

    if (_statusFilter != 'all' &&
        status != _statusFilter) {
      return false;
    }

    if (_searchText.isEmpty) {
      return true;
    }

    final String employeeName =
        data['employeeName']
                ?.toString()
                .toLowerCase() ??
            '';

    final String employeeId =
        _referenceId(data['employeeId'])
            .toLowerCase();

    return employeeName.contains(_searchText) ||
        employeeId.contains(_searchText);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor:
          const Color(0xFFF7F8FC),
      appBar: AppBar(
        title: const Text('Payslips'),
        backgroundColor:
            const Color(0xFFF04B0B),
        foregroundColor: Colors.white,
      ),
      body: StreamBuilder<
          QuerySnapshot<Map<String, dynamic>>>(
        stream: FirebaseFirestore.instance
            .collection('payslips')
            .snapshots(),
        builder: (
          BuildContext context,
          AsyncSnapshot<
                  QuerySnapshot<
                      Map<String, dynamic>>>
              snapshot,
        ) {
          if (snapshot.hasError) {
            return Center(
              child: Padding(
                padding:
                    const EdgeInsets.all(24),
                child: Text(
                  'Unable to load payslips: '
                  '${snapshot.error}',
                  textAlign: TextAlign.center,
                ),
              ),
            );
          }

          if (!snapshot.hasData) {
            return const Center(
              child: CircularProgressIndicator(),
            );
          }

          final List<
                  QueryDocumentSnapshot<
                      Map<String, dynamic>>>
              payslips = snapshot.data!.docs
                  .where(_matches)
                  .toList();

          payslips.sort(
            (
              QueryDocumentSnapshot<
                      Map<String, dynamic>>
                  first,
              QueryDocumentSnapshot<
                      Map<String, dynamic>>
                  second,
            ) {
              final DateTime firstDate =
                  _dateFromValue(
                        first.data()[
                            'payrollPeriodStart'],
                      ) ??
                      DateTime(2000);

              final DateTime secondDate =
                  _dateFromValue(
                        second.data()[
                            'payrollPeriodStart'],
                      ) ??
                      DateTime(2000);

              return secondDate
                  .compareTo(firstDate);
            },
          );

          return ListView(
            padding:
                const EdgeInsets.fromLTRB(
              18,
              18,
              18,
              30,
            ),
            children: <Widget>[
              _buildFilters(),
              const SizedBox(height: 18),
              if (payslips.isEmpty)
                const _EmptyPayslips()
              else
                ...payslips.map(
                  (
                    QueryDocumentSnapshot<
                            Map<String, dynamic>>
                        document,
                  ) =>
                      Padding(
                    padding:
                        const EdgeInsets.only(
                      bottom: 12,
                    ),
                    child: _PayslipCard(
                      payslipId: document.id,
                      reference:
                          document.reference,
                      data: document.data(),
                      processing:
                          _processingPayslipId ==
                              document.id,
                      onApprove:
                          _approvePayslip,
                      onReturn: _returnPayslip,
                      onRelease:
                          _releasePayslip,
                      onDownload:
                          _downloadPayslip,
                    ),
                  ),
                ),
            ],
          );
        },
      ),
    );
  }

  Widget _buildFilters() {
    return Container(
      padding: const EdgeInsets.all(15),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius:
            BorderRadius.circular(16),
        border: Border.all(
          color: const Color(0xFFE4E7EC),
        ),
      ),
      child: Column(
        children: <Widget>[
          DropdownButtonFormField<String>(
            initialValue: _statusFilter,
            decoration:
                const InputDecoration(
              labelText: 'Payslip Status',
              prefixIcon:
                  Icon(Icons.filter_alt_outlined),
              border: OutlineInputBorder(),
            ),
            items: const <
                DropdownMenuItem<String>>[
              DropdownMenuItem<String>(
                value: 'all',
                child:
                    Text('All Statuses'),
              ),
              DropdownMenuItem<String>(
                value: 'draft',
                child: Text('Draft'),
              ),
              DropdownMenuItem<String>(
                value: 'pending_approval',
                child:
                    Text('Pending Approval'),
              ),
              DropdownMenuItem<String>(
                value: 'returned',
                child: Text('Returned'),
              ),
              DropdownMenuItem<String>(
                value: 'approved',
                child: Text('Approved'),
              ),
              DropdownMenuItem<String>(
                value: 'released',
                child: Text('Released'),
              ),
            ],
            onChanged: (String? value) {
              if (value == null) {
                return;
              }

              setState(() {
                _statusFilter = value;
              });
            },
          ),
          const SizedBox(height: 12),
          TextField(
            controller: _searchController,
            onChanged: (String value) {
              setState(() {
                _searchText =
                    value.trim().toLowerCase();
              });
            },
            decoration:
                const InputDecoration(
              labelText: 'Search Employee',
              prefixIcon: Icon(Icons.search),
              border: OutlineInputBorder(),
            ),
          ),
        ],
      ),
    );
  }
}

class _PayslipCard extends StatelessWidget {
  const _PayslipCard({
    required this.payslipId,
    required this.reference,
    required this.data,
    required this.processing,
    required this.onApprove,
    required this.onReturn,
    required this.onRelease,
    required this.onDownload,
  });

  final String payslipId;

  final DocumentReference<Map<String, dynamic>>
      reference;

  final Map<String, dynamic> data;

  final bool processing;

  final Future<void> Function({
    required String payslipId,
    required DocumentReference<
            Map<String, dynamic>>
        payslipReference,
    required Map<String, dynamic> data,
  }) onApprove;

  final Future<void> Function({
    required String payslipId,
    required DocumentReference<
            Map<String, dynamic>>
        payslipReference,
    required Map<String, dynamic> data,
  }) onReturn;

  final Future<void> Function({
    required String payslipId,
    required DocumentReference<
            Map<String, dynamic>>
        payslipReference,
    required Map<String, dynamic> data,
  }) onRelease;

  final Future<void> Function({
    required String payslipId,
    required Map<String, dynamic> data,
  }) onDownload;

  @override
  Widget build(BuildContext context) {
    final String employeeName =
        data['employeeName']?.toString() ??
            'Employee';

    final String employeeId =
        _referenceId(data['employeeId']);

    final String status =
        _normalizeStatus(data['status']);

    final DateTime? periodStart =
        _dateFromValue(
      data['payrollPeriodStart'],
    );

    final DateTime? periodEnd =
        _dateFromValue(
      data['payrollPeriodEnd'],
    );

    final double netPay =
        _readNumber(data['netPay']);

    final String generatedBy =
        _actorLabel(
      data['generatedBy'] ??
          data['preparedBy'],
    );

    final String returnReason =
        data['returnReason']
                ?.toString()
                .trim() ??
            '';

    return Container(
      padding: const EdgeInsets.all(17),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius:
            BorderRadius.circular(17),
        border: Border.all(
          color: const Color(0xFFE4E7EC),
        ),
      ),
      child: Column(
        crossAxisAlignment:
            CrossAxisAlignment.start,
        children: <Widget>[
          Row(
            children: <Widget>[
              CircleAvatar(
                backgroundColor:
                    const Color(0xFFFFF1EA),
                child: Text(
                  _initials(employeeName),
                  style: const TextStyle(
                    color: Color(0xFFF04B0B),
                    fontWeight:
                        FontWeight.w800,
                  ),
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment:
                      CrossAxisAlignment.start,
                  children: <Widget>[
                    Text(
                      employeeName,
                      style: const TextStyle(
                        fontSize: 16,
                        fontWeight:
                            FontWeight.w800,
                      ),
                    ),
                    Text(
                      employeeId.toUpperCase(),
                      style: const TextStyle(
                        color:
                            Color(0xFF667085),
                        fontSize: 12,
                      ),
                    ),
                  ],
                ),
              ),
              _StatusChip(status: status),
            ],
          ),
          const SizedBox(height: 14),
          const Divider(height: 1),
          const SizedBox(height: 13),
          Text(
            '${_formatDate(periodStart)} – '
            '${_formatDate(periodEnd)}',
            style: const TextStyle(
              color: Color(0xFF475467),
              fontWeight: FontWeight.w600,
            ),
          ),
          const SizedBox(height: 6),
          Text(
            'Net Pay: PHP ${netPay.toStringAsFixed(2)}',
            style: const TextStyle(
              color: Color(0xFFF04B0B),
              fontSize: 17,
              fontWeight: FontWeight.w800,
            ),
          ),
          const SizedBox(height: 5),
          Text(
            'Generated by: $generatedBy',
            style: const TextStyle(
              color: Color(0xFF667085),
              fontSize: 11,
            ),
          ),
          if (status == 'returned' &&
              returnReason.isNotEmpty) ...<Widget>[
            const SizedBox(height: 10),
            Container(
              width: double.infinity,
              padding:
                  const EdgeInsets.all(11),
              decoration: BoxDecoration(
                color:
                    const Color(0xFFFFF4ED),
                borderRadius:
                    BorderRadius.circular(10),
                border: Border.all(
                  color:
                      const Color(0xFFFFD6AE),
                ),
              ),
              child: Text(
                'Return reason: $returnReason',
                style: const TextStyle(
                  color: Color(0xFFB54708),
                  fontSize: 12,
                  height: 1.35,
                ),
              ),
            ),
          ],
          const SizedBox(height: 15),
          if (processing)
            const LinearProgressIndicator()
          else
            Wrap(
              spacing: 9,
              runSpacing: 9,
              children: <Widget>[
                OutlinedButton.icon(
                  onPressed: () {
                    onDownload(
                      payslipId: payslipId,
                      data: data,
                    );
                  },
                  icon: const Icon(
                    Icons.download_outlined,
                  ),
                  label:
                      const Text('Download'),
                ),
                if (status ==
                    'pending_approval')
                  OutlinedButton.icon(
                    onPressed: () {
                      onReturn(
                        payslipId: payslipId,
                        payslipReference:
                            reference,
                        data: data,
                      );
                    },
                    style:
                        OutlinedButton.styleFrom(
                      foregroundColor:
                          const Color(
                        0xFFD92D20,
                      ),
                      side: const BorderSide(
                        color:
                            Color(0xFFD92D20),
                      ),
                    ),
                    icon: const Icon(
                      Icons.undo_rounded,
                    ),
                    label:
                        const Text('Return'),
                  ),
                if (status ==
                    'pending_approval')
                  FilledButton.icon(
                    onPressed: () {
                      onApprove(
                        payslipId: payslipId,
                        payslipReference:
                            reference,
                        data: data,
                      );
                    },
                    style:
                        FilledButton.styleFrom(
                      backgroundColor:
                          const Color(
                        0xFF1F5CF5,
                      ),
                      foregroundColor:
                          Colors.white,
                    ),
                    icon: const Icon(
                      Icons.check_rounded,
                    ),
                    label:
                        const Text('Approve'),
                  ),
                if (status == 'approved')
                  FilledButton.icon(
                    onPressed: () {
                      onRelease(
                        payslipId: payslipId,
                        payslipReference:
                            reference,
                        data: data,
                      );
                    },
                    style:
                        FilledButton.styleFrom(
                      backgroundColor:
                          const Color(
                        0xFF039855,
                      ),
                      foregroundColor:
                          Colors.white,
                    ),
                    icon: const Icon(
                      Icons.send_outlined,
                    ),
                    label:
                        const Text('Release'),
                  ),
              ],
            ),
        ],
      ),
    );
  }
}

class _DialogInfoRow extends StatelessWidget {
  const _DialogInfoRow({
    required this.label,
    required this.value,
  });

  final String label;
  final String value;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding:
          const EdgeInsets.only(bottom: 8),
      child: Row(
        crossAxisAlignment:
            CrossAxisAlignment.start,
        children: <Widget>[
          SizedBox(
            width: 105,
            child: Text(
              label,
              style: const TextStyle(
                color: Color(0xFF667085),
                fontSize: 12,
              ),
            ),
          ),
          Expanded(
            child: Text(
              value,
              style: const TextStyle(
                color: Color(0xFF101828),
                fontSize: 12,
                fontWeight: FontWeight.w700,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _StatusChip extends StatelessWidget {
  const _StatusChip({
    required this.status,
  });

  final String status;

  @override
  Widget build(BuildContext context) {
    Color background;
    Color foreground;

    switch (status) {
      case 'released':
        background =
            const Color(0xFFECFDF3);
        foreground =
            const Color(0xFF027A48);
        break;

      case 'approved':
        background =
            const Color(0xFFF0F6FF);
        foreground =
            const Color(0xFF1849A9);
        break;

      case 'pending_approval':
        background =
            const Color(0xFFFFFAEB);
        foreground =
            const Color(0xFFB54708);
        break;

      case 'returned':
        background =
            const Color(0xFFFFF4ED);
        foreground =
            const Color(0xFFB42318);
        break;

      default:
        background =
            const Color(0xFFF2F4F7);
        foreground =
            const Color(0xFF475467);
    }

    return Container(
      padding: const EdgeInsets.symmetric(
        horizontal: 10,
        vertical: 6,
      ),
      decoration: BoxDecoration(
        color: background,
        borderRadius:
            BorderRadius.circular(20),
      ),
      child: Text(
        _formatLabel(status),
        style: TextStyle(
          color: foreground,
          fontSize: 10,
          fontWeight: FontWeight.w800,
        ),
      ),
    );
  }
}

class _EmptyPayslips extends StatelessWidget {
  const _EmptyPayslips();

  @override
  Widget build(BuildContext context) {
    return const Padding(
      padding:
          EdgeInsets.symmetric(vertical: 50),
      child: Column(
        children: <Widget>[
          Icon(
            Icons.description_outlined,
            size: 60,
            color: Color(0xFF98A2B3),
          ),
          SizedBox(height: 12),
          Text(
            'No payslips found',
            style: TextStyle(
              fontSize: 18,
              fontWeight: FontWeight.w800,
            ),
          ),
        ],
      ),
    );
  }
}

String _normalizeStatus(dynamic value) {
  final String raw =
      value?.toString().trim().toLowerCase() ??
          'draft';

  final String normalized = raw
      .replaceAll('-', '_')
      .replaceAll(' ', '_');

  if (normalized == 'pendingapproval' ||
      normalized == 'pending') {
    return 'pending_approval';
  }

  return normalized;
}

String _actorLabel(dynamic value) {
  if (value is Map<String, dynamic>) {
    final String fullName =
        value['fullName']?.toString().trim() ??
            '';

    final String email =
        value['email']?.toString().trim() ??
            '';

    final String role =
        value['role']?.toString().trim() ??
            '';

    if (fullName.isNotEmpty &&
        role.isNotEmpty) {
      return '$fullName (${_formatLabel(role)})';
    }

    if (fullName.isNotEmpty) {
      return fullName;
    }

    if (email.isNotEmpty) {
      return email;
    }

    final String uid =
        value['uid']?.toString().trim() ??
            '';

    if (uid.isNotEmpty) {
      return uid;
    }
  }

  if (value is Map) {
    return _actorLabel(
      value.map<String, dynamic>(
        (
          dynamic key,
          dynamic item,
        ) =>
            MapEntry<String, dynamic>(
          key.toString(),
          item,
        ),
      ),
    );
  }

  final String text =
      value?.toString().trim() ?? '';

  return text.isEmpty ? 'Not available' : text;
}

double _readNumber(dynamic value) {
  if (value is num) {
    return value.toDouble();
  }

  return double.tryParse(
        value?.toString() ?? '',
      ) ??
      0;
}

String _referenceId(dynamic value) {
  if (value is DocumentReference) {
    return value.id;
  }

  final String raw =
      value?.toString() ?? 'employee';

  return raw.contains('/')
      ? raw.split('/').last
      : raw;
}

DateTime? _dateFromValue(dynamic value) {
  if (value is Timestamp) {
    return value.toDate();
  }

  if (value is DateTime) {
    return value;
  }

  if (value is String) {
    return DateTime.tryParse(value);
  }

  return null;
}

String _formatDate(DateTime? date) {
  if (date == null) {
    return 'Not available';
  }

  const List<String> months =
      <String>[
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Oct',
    'Nov',
    'Dec',
  ];

  return '${months[date.month - 1]} '
      '${date.day}, ${date.year}';
}

String _formatLabel(String value) {
  if (value.trim().isEmpty) {
    return 'Unknown';
  }

  return value
      .replaceAll('_', ' ')
      .split(' ')
      .where(
        (String word) => word.isNotEmpty,
      )
      .map(
        (String word) =>
            '${word[0].toUpperCase()}'
            '${word.substring(1).toLowerCase()}',
      )
      .join(' ');
}

String _initials(String fullName) {
  final List<String> parts = fullName
      .trim()
      .split(RegExp(r'\s+'))
      .where(
        (String part) => part.isNotEmpty,
      )
      .toList();

  if (parts.isEmpty) {
    return '?';
  }

  if (parts.length == 1) {
    return parts.first[0].toUpperCase();
  }

  return '${parts.first[0]}${parts.last[0]}'
      .toUpperCase();
}
